// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsalqpfkzzdpbntlbxui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzYWxxcGZrenpkcGJudGxieHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTkyOTIsImV4cCI6MjA2NjE3NTI5Mn0.WzTD5cOMGyCT5aGcvF4fUXLNX7Op0AvkbtpNf5wbYOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);